apiVersion: v1
kind: Pod
metadata:
  name:   pm-metric-processor
spec:
  containers:
    - name: pm-metric-processor
      image: ubuntu
      args: [bash, -c, 'for ((i = 0; ; i++)); do echo "$i: $(date)"; sleep 100; done']
