apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "homeautomation.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "homeautomation.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "homeautomation.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 3
          volumeMounts:
            - name: configmap-volume
              mountPath: "/config"
              readOnly: true
      volumes:
        - name: configmap-volume
          configMap:
            name: homeautomation-configmap
            items:
              - key: "external.properties"
                path: "external.properties"