apiVersion: v1
kind: Service
metadata:
  name: homeautomation-service
  labels:
    name: homeautomation
spec:
  ports:
    - port: 8080
      name: http-port
      protocol: TCP
  selector:
    app: homeautomation
